FROM php:8.4-apache

ENV TZ=UTC
# in some case you shuld change user id (1000)
ENV WWWGROUP=1000
ENV WWWUSER=1000
ENV APACHE_DOCUMENT_ROOT=/var/www/html/public
ENV USERNAME=www-data

RUN apt-get update -y && apt-get install -y cron supervisor unzip libzip-dev libpng-dev libjpeg-dev libwebp-dev libfreetype6-dev libjpeg62-turbo-dev git libicu-dev zlib1g-dev

RUN pecl install redis xdebug \
    && docker-php-ext-configure gd --with-freetype --with-jpeg --with-webp \
    && docker-php-ext-install mysqli pdo pdo_mysql gd zip pcntl intl exif\
    && docker-php-ext-enable mysqli pdo pdo_mysql gd zip pcntl intl redis exif xdebug

# Configure Xdebug
RUN cat << 'EOF' > /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
zend_extension=xdebug.so
xdebug.mode=develop,coverage,debug,profile,gcstats,trace
xdebug.idekey=docker
xdebug.start_with_request=yes
xdebug.log=/dev/stdout
xdebug.log_level=0
xdebug.client_host=host.docker.internal
xdebug.client_port=9003
xdebug.discover_client_host=1
EOF


#install composer
ADD --chmod=0755 https://github.com/mlocati/docker-php-extension-installer/releases/latest/download/install-php-extensions /usr/local/bin/
RUN install-php-extensions @composer-2

RUN a2enmod rewrite \
    && usermod -u $WWWUSER $USERNAME \
    && groupmod -g $WWWGROUP $USERNAME

# docker file description
# build command: docker build -t larado:php8.4-1 -t larado:latest --push .
